### PR TITLE
Temp/sync branches

### PR DESCRIPTION
**Pull request by amaredeus**
syncing develop with main branch

### CODE REVIEW

**Review by austinmitchem — APPROVED** [review]
In the future let's merge hotfixes into develop sooner rather than later.

**Comment by amaredeus** [comment]
> In the future let's merge hotfixes into develop sooner rather than later.

Sooner than 2 days the PR has been open for?

**Review by tikisailor — APPROVED** [review]

**Review by nonsensecodes — APPROVED** [review]
Looks good! Thanks for setting this up, @amaredeus

**Comment by nonsensecodes** [comment]
> In the future let's merge hotfixes into develop sooner rather than later.

I was supposed to set this up before the weekend, but got wrapped up with irl responsibilities. Any way, thank you @amaredeus for picking up my slack. PR is ready to merge.

**Pull request merged**
