### PR TITLE
Feature/guild welcome message

### LINKED ISSUE #34: Notion: DM when member adds Developer Guild role
When a member is assigned the developer guild role, DM them a list of projects from [notion](https://www.notion.so/Dev-Guild-Projects-2d36ac50c02640bda22fbbf72069afe3) and other useful getting started information.

### PR DESCRIPTION
**Pull request by austinmitchem**
Sends direct message to user when they add the Developer's Guild role. Pulls project information from https://www.notion.so/Dev-Guild-Projects-2d36ac50c02640bda22fbbf72069afe3.

welcome

Closes #34

### CODE REVIEW

**Review by nonsensecodes — CHANGES_REQUESTED** [review]
Awesome that we’re close to getting this rolled! @austinmitchem, will you abstract the welcome mat to a separate module in a new folder under events? This way we can add more guilds and have event modules without the `guildMemberUpdate.ts` getting too big too quickly. Thank you so much for working on this 🙏

**Comment by nonsensecodes** [comment]
I refactored the code to pull `sendGuildWelcomeMessage()` into a separate module. This still needs some work, as I'm unsure where the `status: active` is being read from, and despite a `try/catch` for error handling, it crashes when attempting to add the developer's guild role.

Also, we should hold off on merging this into `develop` until we figure out a job queue for anything Notion related. To be continued ...

**Comment by austinmitchem** [comment]
Added queue for notion requests with rate limit of 3 requests per second.

**Comment by nonsensecodes** [comment]
Leave to some small detail to throw a wrench in the whole shebang. @austinmitchem, will you reassess the test cases in light of the notion queue? They're all passing, but apparently the deployment stalls after the tests are done:

```
Cannot log after tests are done. Did you forget to wait for something async in your test?
145
    Attempted to log "Queue is idle.  Size: 0  Pending: 0".
146

147
      14 |
148
      15 | notionQueue.on('idle', () => {
149
    > 16 |     console.debug(
150
         |             ^
151
      17 |         `Queue is idle.  Size: ${notionQueue.size}  Pending: ${notionQueue.pending}`
152
      18 |     );
153
      19 | });
154

155
      at console.debug (node_modules/@jest/console/build/BufferedConsole.js:149:10)
156
      at PQueue.<anonymous> (src/app/api/notion/NotionQueue.ts:16:13)
      
```

**Review by amaredeus — COMMENTED** [review]
Small update, can we add a new entry in docs/CHANGELOG.md under 1.3.0-SNAPSHOT

**Review by nonsensecodes — DISMISSED** [review]

**Review by amaredeus — APPROVED** [review]
Looking smoooth

**Review by nonsensecodes — APPROVED** [review]

**Pull request merged**
