### PR TITLE
add datadog tracer

### PR DESCRIPTION
**Pull request by austinmitchem**
- Adds Datadog tracers

### CODE REVIEW

**Comment by amaredeus** [comment]
Are there any environment variables for QA/PROD?

**Comment by austinmitchem** [comment]
> Are there any environment variables for QA/PROD?

Yes, currently I have them set in Heroku.

**Comment by nonsensecodes** [comment]
> > Are there any environment variables for QA/PROD?
> 
> Yes, currently I have them set in Heroku for serendipity.

Will you set these up in the `env.qa` and `.yaml` files so they're available should we ever need to change our deployment? Everything else looks good and ready to go once this is implemented 👍

**Review by nonsensecodes — CHANGES_REQUESTED** [review]
Changes requested in the commentary on the PR regarding environment variables.

**Comment by nonsensecodes** [comment]
> > Are there any environment variables for QA/PROD?
> 
> Yes, currently I have them set in Heroku for serendipity.

I copied the API Key over to GitHub secrets under `QA_API_KEY`. Will you update the `deploy-qa.yml` file accordingly, please? And update the `env.qa` to match the rest of the integrations? I'd much appreciate it.

**Review by amaredeus — APPROVED** [review]

**Review by nonsensecodes — APPROVED** [review]

**Pull request merged**
